apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  description: Compile Java application with Maven
  params:
    - name: maven-image
      description: Namespace where the image will be pushed
      default: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.15-7
      type: string
  steps:
    - name: maven-build
      image: $(params.maven-image)
      workingDir: /workspace/source
      command:
        - mvn
      args:
        - clean
        - install
        - -DskipTests # Test should be run and recorded in a separate task
  workspaces:
    - description: Persistance Storage between Pods.
      name: source
